language: python
python:
- '3.3'
- '3.4'
- '3.5'
- 3.5-dev
- nightly
install: pip install -r requirements.txt
script: nosetests
env:
  global:
  - secure: hWJEIqdIhaKPVIlRy3gxSX5dX9ykmN6AM09EzjgegGSSnzaV6WJMKttvQhZrwUVk1XnXgjw8cbP0szqoVF3hkvNMoejdJ5zBhCpM8HSJat8ze0DmDLLpYg5Ivc5c4Y1JqAQPN+ol9wEt9NNQmfOngP2CnLyfTZtJWOtYmJruXHwu/03tpbUHGZt8gWSOCztvjbtxzi0lpzcfZ/9FkfGQ9541MPJUAdoiPyiwVQguiklbGF47we8Gko9nTBjyBRCr1eZxGSMqR9AkGYoUL7RLSj4V9xbKoNnHjamtw709F5AiSNF76Qe+za+dXXCugsZDruGok4ViN3inI7QI6sbuGVAPB9cqVAqWXKS23Yzrw/kiRoQ2YkOEFl4m+AgwRTdW/VPyh2o1CQ8IzfxP25hHwinyeI8qu3BLlZM8fjdpp/EiyXwogV6Zsvcb5T62HbjMnCTXsJ3H4kJk0n7UtgoMVA2mdz5kP6BKWZkG75Z/gQBnNvbZ0e5JCk7gfc3z7yDqqAzrEYkGHdPA0JOMTK7CqCiwFuw5Gy/3AclEoe8+VldBbjhEG2xzz4izD9hizkJiCv8Etdn3Ol8QagN5bdkWpOLlBvOe6fzvolaSAVInTEsDzbyZFjdfNIh8Y2eIb6zQhovk+2bmfN5PRG6TejzlOkPPjT57JqrInOwWgCiGM0w=
  - secure: 3Paz1IcBB4MhhYKkcC87vBH0QUk2uSMz9oosF3AVeeuROufdep+cms9Mx80+qVEvY7xV1CXSSFbfVzwc0qdczacmMDHOZzU7tjzSUkTxYP1dN0Fu4HjUcKc3WBOhCH4l6vTi5YLscVsyvL4UNgVfnm1OjKk2hNZyreDeYj6ffsKhwW5WAto2aH8ADEkDKWatDzXkaSpbEzcbe62OD42SQmRPNCtKVBdEVnjDvfcCLJi7Euy5ln5gm37IOjr9/6BuYQVRr/NOtYHQPgz87qWLAMHD3wZbijbIIQCLNNLpNk71UCNLZijOR+iUAIckQSD9XLuZHhRnVpe3NgukRaeQ547603pnjT1Wv0455aCENFgIkxBRK8PyaSHbnmOPWV4VTVLDjB449qnMViOAd3TYZ31UAI1OvehBdXrd9rYe8eXvH2pSsB1IqrrhhjaKGeccyu/9NTETMgl8RHH8yl9C6xuv0cgzVKp5oh2DbjzONT2NK3Yz1sGUdGOcOJt3qynUyevmTKlhGI5n3jVz/E++0lxn85XSBniNTBTjyA5VCFnMK8+J+uC9vl5a5CIMU0bLesCSwTfiAdsWIAmu1iMY+biq4cPRW2MP2HgQNQlmX4JvjOqopdqnnho6TM9nHw8crjlT5Omn31Wc8Foi2x8td6dKYIiWd+y7YI1NgIEsD1M=
