language: python
python:
  - "2.7"
  - "3.3"
  - "3.5"
git:
  submodules: false
before_install:
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init --recursive
- sudo apt-get -qq update
- sudo apt-get install -y pandoc
install: make init
cache: pip
script: make test
env:
  global:
  - secure: V7dR6IVAnEAGqcEVOaH97jzB2qxUssqRY7jHt6HbgJWVYrdmZ3r2F42UVCUFK/8w5WHlpg4v/HKew+G8FXVIq0jhtJuNz6sA6ODsd+VldmjddtACa+t7opvwfgdcXRibeI0MZ1YW9Y/tYVkIj5zeinxfiMWCykzvRAALXD9CxrMrdmVR2XBfk5KGgAQQGUnZNoZsI17Ojzz+4CXQhZOwo/giZP6xxa5bPPQ7wgu6h3Q2aOiMQfFYHqx91lrZSnlQVjzxpH7MI7GTQZBs/1mqP4vFtjwyAdkcGKqEY8N+yvQjNRABv1Vhr8AGphDe1hPx8dm8A8L7knEvuQoYKL3RPTXKqpWPHWSJ9dRFhj4O9A4zOFK39cCAkRCRW42V1mvwmTWArWh/MoHXJjdLa+pBNls2fEwoUg4lQBxPLwuka+UWQfUMbBiq4Z4pU78V8BHd6e32yDaeh4HRP+w6K0K74n99PSF4tERxyIvY8gxX0y8ENN7PTxI61tVZP6ABOAaUUV23KhC3LHleUjmXbdOQzbYF5glr3HlUTC0pYd7fj9MjbL6seT/A7WARqKC4YGp64r71dmy5E/U7A3PmlCOAvDouvJwdNA1iE+nGPeMkuTACrC8fS2ZwlqL2vv0mKzmpNSOXCsQM+QIn8/kY5/ZIoFFz7omayMP2UNN7QMpSssI=
deploy:
  provider: pypi
  user: ops
  password:
    secure: BV855ZvX9A+93Zn3o8OjbxJCJ4GiHjcPLzerd4TiuBHFh4e78i9UAcjCS4f1GjgdDe+QM+c/PKxHDI0Fgk/QcNSjAWNPyreY5qNfScLVbfD2GGWoi71Oqt2Yo82lGOGEQjbiOruJhbnnPTJ0tYCedtYsgy/aDAK5Asl9lpzlZm0mH+5FNJbyuPWr0KkWh3oR5kZ9yaO3kSAvTkn3gCS4E14s/n+qYCBQPaHHmDCDoE6J021kHTIqXQpTXY39Xoc1q5z+cJXJ01L2c/z/MDRbFrLvetglqD6sru9ZwSV1U9HUMbzuHv/+yrxydyuZoRE/IHfD8BfWkq+A8dGLytLs0R4EJlVS2bTBCGIIRQ+STWlFl8JjkG4ONkzeCWR0VppEKMQ41YGU7pexm7Z7c7dwxsTsOU5wV5TNS3jHJTvbkVBWtIrJSgN//DDTIwo3kP/ayeZ+Ndz29b17/MTkCScUXxU0QD5Qril3JMPEJo/O1g1pw7FcvaAWRkcGzTyi1Nt//6dqGWTvTX89WZ5F9mnwDN7PL3WPqVNIg/eZq2pQIdT6S6iiVdS9pmrFAJ+u51kV4Udedp70HlR6RxxWILCKmP3wiV9YA9NX8vk8woOoWq9WCJ89/oI2VcOPOvwnUXiLEbQqb89uqGpCzhwluKZrlSt+y6tHXsmu0P47MwDwpn0=
  distributions: bdist_wheel
  on:
    tags: true
    branch: master
    python: "3.5"
notifications:
  slack: craft-ai:ZNnQErHJhw40oKmphy3fNGza
  email:
  - ops@craft.ai
