language: python
python: '3.5'
git:
  submodules: false
before_install:
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init --recursive
install:
- pip install --upgrade pip
- pip install -r requirements.txt
script: sh run-tests.sh
env:
  matrix:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py35
  global:
  - secure: OLQOjsYKD5NOTDaLt6BpAJfpbr1vGAXdRO05hl115Aoqs5eJzppc7XaOazTGnd13jJ2g7Ot32upMOow+9AzBYGRHuc/Rjy3fF+yaaiafkH3BgR0cC9bL90nlm5CZB9tRz8dW5a5Iv43ElS34MddskR+GQPLInqBfpAQSBjgUEEDsVbMUp+gOdqDNa6eaclv5xSACzyPi5G2duc52sOOT44xUJ9bbBE0s/byGq2le3223uLFdSi44WrclEuO5NaD8KaE0FPXrf6Mwlcd/Kp87sSM5USfToCcQ6QYxewbOR0Hr7/2vnXbpW3trWs+oH1ItERv9AlFIwMBgFZgGQx62Qhy0gVcGN+v2B2LBogKMG0CnUljfTJd/wii9ayhF3a6NCioeZQ4wuOTGMK1IVywbR9tRZ1ErfDDDxcfbhdL16K7r3NEtJAwREqutcI7PPnRJ9L6pTJ4CBofBQ4DoxyZKkJHZvw0acnsOhY1qY3v4RK4Wb4IoUOMlJCxmKCSHeTtyEj64wJAwu8OrlFPGOIO9UN7BTG3KUfpN8qIQ/4jIwr+RH4A2EpQjROHcxRTd+rlFtnhPjwUrf+OSGCsypqAYo0yNWCLErLshSzvi1sXCNUWYcWzx92ZsQMOUuNBHdavOuYvXtd7e6j0sEsAVkjtwEJoDHZa/gdhFmzG59OHgUoY=
  - secure: hgv3U3IgGmgoTs6i12iwzLUAU5ti8UN7MQYU/x8DXgSXza7r/y/c9Xq8d5WtOG98kToYs/lKeEjIAKMIyEprsmwL0hCYAWSNrlOooHTZYOH4xkJ0g20B+f50UBYUUktR3E5zoEsGFC8zjQaKDKEsmXVRnMG1PX8tnft+bXsO6Eed9B5XR/YLsDC2aYSGU8G+zgowBvLKiiHk4Ob0CoKVxhbSR4c0GcH7aXUpd3Otg6IhHuFw5op5W+tYANqmWpC2+X+jw+l+iuwRdQoWefvqRH71AEq+4gh1u0QN2Ql02H5TzgSvxFdfhNjYaRy/cjKyHDIujyGDTx7haLwWz7M0AcGbz2QEkJL/ApdOe7BXf0jdyMH57w8gPwKfoKdk+bKM6hW68Ink7OkwjrdP9rzg2MRNacpl77+F/Kyd7sUmUfzyFzO5SIR/wM1gYzaXCfrFF9adEKQwg3d0lTFg/WyiOMlYr9rhr6MR/rSOgvaCxF27N6AXRismCWezLEGV+Ikl8rOKAjxwIqAo2WxTKJ/SBY6VszAi9cKXpg/2w+LXF5EoqykjVQVe5Iye5xdD7BwMqX3rWeJzHV6p4eSuLElGsqkYhkFmFLc5IHtxiOpdSwt5jnQPqhDOMLGLr46tY/m/UmvW6BZVblvSNyhGsIPxC9vncKZD7mHhZGUTqFux3c0=
  - secure: I/SmfJFsJ+idXKoSzwcxaG9ndIrh3Xr+qC+5YwKov2ryk0QwkbInIMvaLPd2PgUd3fgxBgb47IUV3dQlIEQdsUQ9XfJlRQ186LiH+fzvs8tiS4Fdp/1MzlbYwzy5Fs8+8aMn5qibmi24BlpcfcfKJ5iCHAvtbmk6QaCN98GqQqpWbRO/o5jDCCvKvP+FLRu/wXdsQrNV4a0ds5lfea5Sn3MVXRPCvrfD8q4MoxVzTbwzwNygF0cx5+eIMQtVd66t5rAdN6ZksfiA+XvjvrfBrvI0tGmVVNw7If4BjWLkLRfwoqJPkQY67k7ZuW72rGpHBpWG/jcDGe00TUvCb+mcq+jd8uawZwJVVRqJbSJTbNXKR6uJGa0Y7VjtrZFBo4m26NEvATSzN8r4jHHx+R1lxgo16+euAL0I7Re8Yx2mxed+mnVFc1vbJ+dtvWpu/7k16s3uLfYmICMm01tD/k0QLxNicg5PYhvQyeVC6Istd9o4gCUWwiJKwGmY2Fp8NQAT5p5OVRCVHNYH6p7FDukyCjR0gTWZNxzrXDspRzYKI8+ltB+ALFExQVnWCI5Mt1Dcefx2P4jQ7UuLs33pW/PchuZWGKtSfzjSqIObS00PS7A9v3xWdFM9uiWkFVPlT4hPsF+7xnfgBhid8HVNfuk/sQpXhiJmG2qg+V1u5i3zZoo=
before_deploy:
- git describe --tags --match='v*'
deploy:
  provider: pypi
  user: ops
  password:
    secure: BV855ZvX9A+93Zn3o8OjbxJCJ4GiHjcPLzerd4TiuBHFh4e78i9UAcjCS4f1GjgdDe+QM+c/PKxHDI0Fgk/QcNSjAWNPyreY5qNfScLVbfD2GGWoi71Oqt2Yo82lGOGEQjbiOruJhbnnPTJ0tYCedtYsgy/aDAK5Asl9lpzlZm0mH+5FNJbyuPWr0KkWh3oR5kZ9yaO3kSAvTkn3gCS4E14s/n+qYCBQPaHHmDCDoE6J021kHTIqXQpTXY39Xoc1q5z+cJXJ01L2c/z/MDRbFrLvetglqD6sru9ZwSV1U9HUMbzuHv/+yrxydyuZoRE/IHfD8BfWkq+A8dGLytLs0R4EJlVS2bTBCGIIRQ+STWlFl8JjkG4ONkzeCWR0VppEKMQ41YGU7pexm7Z7c7dwxsTsOU5wV5TNS3jHJTvbkVBWtIrJSgN//DDTIwo3kP/ayeZ+Ndz29b17/MTkCScUXxU0QD5Qril3JMPEJo/O1g1pw7FcvaAWRkcGzTyi1Nt//6dqGWTvTX89WZ5F9mnwDN7PL3WPqVNIg/eZq2pQIdT6S6iiVdS9pmrFAJ+u51kV4Udedp70HlR6RxxWILCKmP3wiV9YA9NX8vk8woOoWq9WCJ89/oI2VcOPOvwnUXiLEbQqb89uqGpCzhwluKZrlSt+y6tHXsmu0P47MwDwpn0=
  distributions: bdist_wheel
  on:
    tags: true
    branch: master
sudo: false
addons:
  apt_packages:
  - pandoc
notifications:
  slack: craft-ai:ZNnQErHJhw40oKmphy3fNGza
  email:
  - ops@craft.ai
